### ISSUE TITLE
Problem compiling controller on mac OS X

### ISSUE THREAD

**Issue by SmBito** [kul-forbes/nmpc-codegen-python#1]
I tried to run the demo files but non of them run correctly! I got several errors!
for example the error in the following photo is after running the file: _**trailer_simulations_python.py**_
![simulator object has no attribute nmpc_python_interface](https://user-images.githubusercontent.com/34525406/51270261-b441b400-19c4-11e9-8740-397477726267.png)

P.s: I'm using _Mac os_ and tried to change the python interpreter (2.7, 3.6 and 3.6) but nothing helps!

**Comment by MelisWillem** [comment]
Please provide the casadi version your using. This python error indicates something went wrong when building the C code, most likely Casadi related problem.

**Comment by SmBito** [comment]
I am using casadi version: 3.3.0
python: v-3.6.8
numpy: v-1.16.0

**Comment by SmBito** [comment]
I've noticed also that the message "**not using visual studio**" is shown up after the execution!
I'm using, however **Visual Studio Code**!!!

Part of the code in "**simulator.py**":
```
class Simulator:
    def __init__(self,nmpc_controller_location,option=""):
        self._nmpc_controller_location=nmpc_controller_location
        if (option == "visual studio"):
            self._visual_studio = True
            print("using visual studio")
        else:
            self._visual_studio = False
            print("not using visual studio")
```

**Comment by MelisWillem** [comment]
First of all clean out the "test_controller_builds" folder, it seems you ran the script first in your downloads folder and then moved it. The CmakeCache.txt now has wrong path's in it. By removing "test_controller_builds" you eliminate all this old cache.

The "not using visual studio"  is a undocumented feature, it refers to the Microsoft build system. Basically if enabled it will use a visual studio solution and Microsoft compiler to build the controller code.

Visual studio Code is just an editor, something completely different from the visual studio IDE.

**Comment by SmBito** [comment]
I deleted the "test_controller_builds" folder but I still get some errors, which are attached in the pdf file!

[terminal_out(TwoCircTrailer)_after_dele_test_controller_builds.pdf](https://github.com/kul-forbes/nmpc-codegen-python/files/2772591/terminal_out.TwoCircTrailer._after_dele_test_controller_builds.pdf)

**Comment by MelisWillem** [comment]
This error is where things go wrong:

`Undefined symbols for architecture x86_64:  "_casadi_interface_g_proxg", referenced from:      _proximal_gradient_descent_get_direction in libPANOC_lib.a(proximal_gradient_descent.c.o)      _proximal_gradient_descent_get_new_residual in libPANOC_lib.a(proximal_gradient_descent.c.o)      _proximal_gradient_descent_forward_backward_envelope in libPANOC_lib.a(proximal_gradient_descent.c.o) ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) make[3]: *** [libpython_interface.dylib] Error 1 make[2]: *** [CMakeFiles/python_interface.dir/all] Error 2 make[1]: *** [CMakeFiles/python_interface.dir/rule] Error 2 make: *** [python_interface] Error 2 -- Detected the following casadi files: cost_function_derivative_combined.c;cost_function.c;integrator.c -- No main.c detected in project root folder -- Configuring done`

il look at it over the weekend, could be problem specific to apple's toolchain

**Comment by SmBito** [comment]
I just tried to run the code with commenting out the lines 54 and 57 (which are these two below lines) , the code compiled with no error! and the output figure are shown below.
Maybe this gives some help!

```
state_history = simulate_demo(trailer_controller,initial_state,reference_state,reference_input,obstacle_weights)

example_models.trailer_print(state_history)
```
![screenshot 2019-01-18 at 15 42 04](https://user-images.githubusercontent.com/34525406/51393283-9cd70800-1b37-11e9-9a39-1e87b05be8b2.png)

**Comment by MelisWillem** [comment]
yea the C-code doesn't get compiled, so python can't load the compiled library (no shit ;) )

**Comment by MelisWillem** [comment]
okey, i need you to send me the generated controller files.
In test_controller_builds you will find a folder with the C files in it. 
Zip it and upload it somewhere (dropbox? whatever you want), so i can download it and run it.

**Comment by SmBito** [comment]
I zipped the whole "test_controller_builds"
https://www.dropbox.com/sh/tidipc0oc3txk3v/AACvzZYAHmThVEezXHLpNWoJa?dl=0

**Comment by MelisWillem** [comment]
The controller compiles on my pc, you should do the following:
go into the /test_controller_builds/demo_controller folder
empty the /test_controller_builds/demo_controller folder/build folder (do NOT remove the build folder itself, just whatever is in it)

Open a terminal in the build folder, run "cmake .." and then "make clean all"

**Comment by SmBito** [comment]
I did exactly what did you say!
After running `cmake ..` I got the following:

> -- The C compiler identification is AppleClang 10.0.0.10001044
> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
> -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detected the following casadi files: cost_function_derivative_combined.c;cost_function.c;integrator.c
> -- No main.c detected in project root folder
> -- Configuring done
> CMake Warning (dev):
>   Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
>   --help-policy CMP0042" for policy details.  Use the cmake_policy command to
>   set the policy and suppress this warning.
> 
>   MACOSX_RPATH is not specified for the following targets:
> 
>    python_interface
> 
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Generating done
> -- Build files have been written to: /Users/Mac/nmpc-codegen-python-master/test_controller_builds/demo_controller/build



and for `make clean all`, I got:

> Scanning dependencies of target CASADI_lib
> [  6%] Building C object casadi/CMakeFiles/CASADI_lib.dir/cost_function_derivative_combined.c.o
> [ 12%] Building C object casadi/CMakeFiles/CASADI_lib.dir/cost_function.c.o
> [ 18%] Building C object casadi/CMakeFiles/CASADI_lib.dir/integrator.c.o
> [ 25%] Linking C static library libCASADI_lib.a
> [ 25%] Built target CASADI_lib
> Scanning dependencies of target PANOC_lib
> [ 31%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/buffer.c.o
> [ 37%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/casadi_interface.c.o
> [ 43%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/lbfgs.c.o
> [ 50%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/lipschitz.c.o
> [ 56%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/matrix_operations.c.o
> [ 62%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/nmpc.c.o
> [ 68%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/panoc.c.o
> [ 75%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/proximal_gradient_descent.c.o
> [ 81%] Linking C static library libPANOC_lib.a
> [ 81%] Built target PANOC_lib
> Scanning dependencies of target python_interface
> [ 87%] Building C object CMakeFiles/python_interface.dir/python_interface/nmpc_python.c.o
> [ 93%] Building C object CMakeFiles/python_interface.dir/python_interface/timer_mac.c.o
> [100%] Linking C shared library libpython_interface.dylib
> Undefined symbols for architecture x86_64:
>   "_casadi_interface_g_proxg", referenced from:
>       _proximal_gradient_descent_get_direction in libPANOC_lib.a(proximal_gradient_descent.c.o)
>       _proximal_gradient_descent_get_new_residual in libPANOC_lib.a(proximal_gradient_descent.c.o)
>       _proximal_gradient_descent_forward_backward_envelope in libPANOC_lib.a(proximal_gradient_descent.c.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [libpython_interface.dylib] Error 1
> make[1]: *** [CMakeFiles/python_interface.dir/all] Error 2
> make: *** [all] Error 2

**Comment by MelisWillem** [comment]
Ha well at least we know what is going wrong, somehow your linker can't link some stuff. Strangely enough this only happens on your mac, and not on mine. Not sure why yet.

**Comment by SmBito** [comment]
I've tried the same code with different machine, but it doesn't work either (Windows 10, Python: 3.6.8 -and Casadi: 3.3.0). I got the following error.

```
GENERATING output folders of controller:
GENERATING PANOC
GENERATING static globals
GENERATING python interface
GENERATING Build system
Generating globals file at: ../test_controller_builds/demo_controller/globals/globals_dyn.h
generating g-type function
generating proxg-type function
not using visual studio
-- The C compiler identification is GNU 6.3.0
-- Check for working C compiler: C:/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Detected the following casadi files: cost_function_derivative_combined.c;cost_function.c;integrator.c
-- No main.c detected in project root folder
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/test/Documents/Workplace/nmpc-codegen-python-master/test_controller_builds/demo_controller/build
Scanning dependencies of target PANOC_lib
[  6%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/buffer.c.obj
[ 12%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/casadi_interface.c.obj
[ 18%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/lbfgs.c.obj
[ 25%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/lipschitz.c.obj
[ 31%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/matrix_operations.c.obj
[ 37%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/nmpc.c.obj
[ 43%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/panoc.c.obj
[ 50%] Building C object PANOC/CMakeFiles/PANOC_lib.dir/proximal_gradient_descent.c.obj
[ 56%] Linking C static library libPANOC_lib.a
[ 56%] Built target PANOC_lib
Scanning dependencies of target CASADI_lib
[ 62%] Building C object casadi/CMakeFiles/CASADI_lib.dir/cost_function_derivative_combined.c.obj
[ 68%] Building C object casadi/CMakeFiles/CASADI_lib.dir/cost_function.c.obj
[ 75%] Building C object casadi/CMakeFiles/CASADI_lib.dir/integrator.c.obj
[ 81%] Linking C static library libCASADI_lib.a
[ 81%] Built target CASADI_lib
Scanning dependencies of target python_interface
[ 87%] Building C object CMakeFiles/python_interface.dir/python_interface/nmpc_python.c.obj
[ 93%] Building C object CMakeFiles/python_interface.dir/python_interface/timer_windows.c.obj
[100%] Linking C shared library libpython_interface.dll
[100%] Built target python_interface
-- Detected the following casadi files: cost_function_derivative_combined.c;cost_function.c;integrator.c
-- No main.c detected in project root folder
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/test/Documents/Workplace/nmpc-codegen-python-master/test_controller_builds/demo_controller/build
Compiling python interface for Windows using MINGW: ../test_controller_builds/demo_controller/build/libpython_interface.dll
Failed to load the dll, are you sure python and the toolchain are compatible?
Traceback (most recent call last):
check if they both are either 32bit or both 64 bit
  File "C:/Users/test/Documents/Workplace/nmpc-codegen-python-master/demos/TwoCircTrailer.py", line 54, in <module>
    state_history = simulate_demo(trailer_controller,initial_state,reference_state,reference_input,obstacle_weights)
  File "C:\Users\test\Documents\Workplace\nmpc-codegen-python-master\demos\demo.py", line 72, in simulate_demo
    sim = tools.Simulator(trailer_controller.location)
  File "../src\nmpccodegen\tools\simulator.py", line 102, in __init__
    self.nmpc_python_interface.simulation_init()
AttributeError: 'Simulator' object has no attribute 'nmpc_python_interface'
Exception ignored in: <bound method Simulator.__del__ of <nmpccodegen.tools.simulator.Simulator object at 0x000002331CB55940>>
Traceback (most recent call last):
  File "../src\nmpccodegen\tools\simulator.py", line 105, in __del__
    self.nmpc_python_interface.simulation_cleanup()
AttributeError: 'Simulator' object has no attribute 'nmpc_python_interface'

```
![annotation 2019-01-24 002051](https://user-images.githubusercontent.com/34525406/51643796-1de63300-1f6e-11e9-9172-cfd1720cd4b3.jpg)

**Comment by SmBito** [comment]
I tired also what you've mentioned before: `cmake ..` & `make clean all`, it seems that these two steps work well! 
![annotation 2019-01-24 000514](https://user-images.githubusercontent.com/34525406/51643154-cfd03000-1f6b-11e9-8215-82d382be666a.jpg)

**Comment by MelisWillem** [comment]
and do you get it when you run the normal demo's? https://github.com/kul-forbes/nmpc-codegen-python/blob/master/demos/demo1.py

**Comment by MelisWillem** [comment]
Also that's a 32 bit gcc compiler, is your python 32 bit?, i'v had it happen before myself. You need Mingw-64, i recommend you use https://www.msys2.org/ to install mingw-64.

**Comment by MelisWillem** [comment]
I am going to close this issue, it seems that this is "user error" as in a wrongly configured tool chain.
